### ISSUE TITLE
JSON-LD context link is down

### ISSUE THREAD

**Issue by wmurphyrd** [w3c-ccg/security-vocab#107]
https://w3id.org/security/v1 , which redirects to https://w3c-ccg.github.io/security-vocab/contexts/security-v1.jsonld , is currently returning 404

**Comment by lukehowkins** [comment]
I raised a similar issue in: https://github.com/w3c-ccg/w3c-ccg.github.io/issues/23

**Comment by peacekeeper** [comment]
> We changed our production site to point at

I don't think production sites should rely on hosted JSON-LD contexts to be available. Your production site should cache a copy of the context locally.

**Comment by nightpool** [comment]
While Mastodon does cache a copy of the context locally, this is a big issue for other members of the Fediverse that rely on the security context to parse JSON-LD signatures, raised here in the SocialCG irc: https://matrix.to/#/!GwINGSasznCfuVLHqd:cybre.space/$16211662412689JOuDT:feneas.org?via=cybre.space&via=matrix.org&via=feneas.org

**Comment by tplooker** [comment]
@wmurphyrd @nightpool appears this may have been an issue with GH pages with the recent change from master to main branch, I have refreshed this publish setup and things now appear to be working again, please re-open if this is still an issue
