### ISSUE TITLE
Add Lint Config

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/security-vocab#16]
The lint configuration used for this module should be checked into source, optional githook should be added to block any commit that breaks the linter.

**Comment by msporny** [comment]
@davidlehn @mattcollier could we get our linter config set up for this repo? Specifically for the code examples in the README.md and JSON file (if possible).

**Comment by OR13** [comment]
@gannan08 I know you just did this for VC Examples... possible for you to do it here as well :) ?

**Comment by gannan08** [comment]
@OR13 Sure, let me see what I can cook up for this.

**Comment by gannan08** [comment]
See https://github.com/w3c-ccg/security-vocab/pull/34.

**Comment by OR13** [comment]
implemented.
