### ISSUE TITLE
Less common hashing algorithm for the message in Ed25519Signature2018

### ISSUE THREAD

**Issue by kdenhartog** [w3c-ccg/security-vocab#21]
In Ed25519Signature2018 it's defined that SHA256 should be used as the prehash function of the message. However, [FIPS 186-5](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf) and in [OpenSSL](https://github.com/openssl/openssl/blob/97b50f67f212589661c9f1edd5285822c6cc642b/crypto/ec/curve25519.c#L5447) it's defined that SHA512 should be used for this prehash function.

I propose that we define Ed25519Signature2020 to modify the algorithm and prepare to deprecate Ed25519Signature2018

[RFC8032](https://tools.ietf.org/html/rfc8032#section-3), did not specify this (it provided suggestions through example only) which is how the ambiguity occurred.

@dlongley @msporny @mikelodder7 thoughts?

**Comment by mikelodder7** [comment]
I agree

**Comment by msporny** [comment]
> I propose that we define Ed25519Signature2020 to modify the algorithm and prepare to deprecate Ed25519Signature2018

+1 to this. Yes, this came up the other day. There is a desire to do a few minor corrections to this cryptography suite in the next few months, namely:

* Changes like the one you mentioned.
* Removal of `jws` and replacement w/ proof value. The JWS stuff was an experiment to see if we could unify the JOSE community and the Linked Data Security community. The attempt has failed for this cryptosuite, but the work is being carried on in [JwsSignature2020](https://lds.jsld.org/contexts/)... so we'd like to push all JOSE stuff to that cryptography suite and keep the Ed25519 stuff simpler and more auditable.

The problem is that Ed25519Signature2018 is deployed in production, so changing it at this point is probably not a good idea. That said, this is exactly what the cryptosuites were designed to do... so let's put some effort into Ed25519Signature2020 and fix the things we've learned from over the past several years. Nothing breaks in the ecosystem and we're left with something that all of us like a little bit more.

**Comment by dlongley** [comment]
Note that Ed25519Signature2018 *does* use a SHA512 in the way @mikelodder7 noted. The linked data signature message works like this:

message = SHA256(canonicalized data) + SHA256(canonicalized proof meta data)

This is currently consistent across all the linked data signature types (RSA, ed25519, secp256k1, secp256r1, etc.) *Then* that "message" is signed using whatever signing algorithm, which typically includes hashing of the "message". So Ed25519Signature2018 requires that libraries internally SHA512(message) and then sign -- and this is what implementations do.

**Comment by kdenhartog** [comment]
> Note that Ed25519Signature2018 _does_ use a SHA512 in the way @mikelodder7 noted. The linked data signature message works like this:
> 
> message = SHA256(canonicalized data) + SHA256(canonicalized proof meta data)
> // note that this message is 64 bytes long
> 
> This is currently consistent across all the modern linked data signature types (RSA, ed25519, secp256k1, secp256r1, etc.) _Then_ that "message" is signed using whatever signing algorithm, which typically includes hashing of the "message". So Ed25519Signature2018 requires that libraries internally SHA512(message) and then sign -- and this is what implementations do.

Ahh then I would think all we need to do then is update the language in Ed25519Signature2018 to make that a bit more clear and start 2020 to make some of the changes proposed by @msporny. I also recently proposed a change over email to Manu around the layering of signature suites and keys. I'd like to discuss that more broadly as well with the community and potentially start using that layering in the 2020 version.

**Comment by peacekeeper** [comment]
I was also under the impression that `Ed25519Signature2018` already uses SHA512. I wrote this crypto suite specification a while ago:

https://w3c-ccg.github.io/lds-ed25519-2018/#the-ed25519-2018-signature-suite

So it appears the language in https://w3c-ccg.github.io/security-vocab/#Ed25519Signature2018 is wrong.

**Comment by OR13** [comment]
I have removed the dupe, but looking around, it seems like the js implementation of Ed25519Signature2018 use sha-256... https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/suites/LinkedDataSignature.js#L223

This createVerifyData goes into the detached jws, here: https://github.com/transmute-industries/lds-jws2020/blob/master/src/__tests__/detached-jws.spec.js

as mike pointed out, jws is gonna hash it again anyway... but the algorithm used in createVerifyData needs to be specified correctly.... for example, we use sha-256 for https://lds.jsld.org/contexts/#suite-details

Our suite extends "LinkedDataSignature" so we inherit createVerifyData from DBs implementation.

Previous signature suites, we implemented createVerifyData manually:

https://github.com/transmute-industries/Ed25519Signature2018/blob/master/src/createVerifyData/index.js#L9

signatures will not interop if a different hash algorithm is used for createVerifyData.

This is why things like: https://tools.ietf.org/html/rfc7520

are useful... 

how do we resolve this issue? we we update the crypto suite registry to say sha-256?

**Comment by peacekeeper** [comment]
> it seems like the js implementation of Ed25519Signature2018 use sha-256

> how do we resolve this issue? we we update the crypto suite registry to say sha-256?

I think @dlongley 's earlier comment answers this. There is SHA-256 hashing during the RDF normalization step which creates the "input message", and then there's SHA-512 hashing during the signing step.

What I'm not sure about is which one of the two is considered the ["message digest algorithm"](https://w3c-ccg.github.io/ld-proofs/#dfn-message-digest-algorithm) according to the LD Proofs spec...

**Comment by OR13** [comment]
its the one that is used in createVerifyData... the one I linked above... the one used during the signature is the one defined by the JWS alg (https://tools.ietf.org/html/rfc8032 --- its sha512 afaik),

**Comment by OR13** [comment]
Can I close this issue now?

**Comment by OR13** [comment]
I'm closing this, as its not actionable. If you are interested in defining Ed25519Signature2020, please create a spec and get to work :) feel free to link back to this issue if you desire.

**Comment by kdenhartog** [comment]
Sorry I didn't get notified when you assigned this to me. I'm satisfied with the resulting discussion and agree the action would be to define a new Ed25519Signature2020, but want to continue discussion on two other topic first. Namely, whether we should be decoupling key representations (base58, jwk, etc) from the signing algorithm (EdDSA, EcDSA, etc). Additionally, how should we be categorizing signing algorithms? Should we classify it as EdDSASignature2020 and support the whole lot of the signing algorithms or just stick to the pattern we've followed.

I'm generally of the opinion that we should decouple key representation and keep the classification of signing algorithms as is. I'll open a separate issue to discuss this further though.

**Comment by OR13** [comment]
@kdenhartog you may also want to comment here: https://github.com/w3c-ccg/security-vocab/issues/32
