### ISSUE TITLE
Define sameAs

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/security-vocab#44]
Useful for describing that 2 subjects are the same entity (id field associated with a verification method)... as discussed at the F2F yesterday.

We should define it here, in the did spec registries and in core with normative text.

**Comment by dlongley** [comment]
To be clear, this would be for describing that 2 *subjects* are the same.

**Comment by OR13** [comment]
Yes, I was trying to make it clear that his would also apply to linked data signatures that do not use DIDs.... one of the most valuable use cases for this is https://auditor.example.com/inspector/123 === did:example:456.

**Comment by dlongley** [comment]
+1 ... I don't think "subjects" or "controllers" are necessarily DID-specific (they are in DID land of course), but I think "sameAs" is a property that would appear on a subject (whether it is identified by a DID or non-DID URI) -- and link it to another subject (again, identified by a DID or non-DID URI). And, I believe, it's still an open question as to whether or not we need a property and definition separate from "owl:sameAs" or if we can just use that vocabulary.
