### ISSUE TITLE
Add MerkleProof2019 to security-vocab

### ISSUE THREAD

**Issue by lemoustachiste** [w3c-ccg/security-vocab#65]
Hi,

[Blockcerts](https://www.blockcerts.org/) v3 implements Verifiable Credentials standard, and uses [MerkleProof2019](https://w3c-ccg.github.io/lds-merkle-proof-2019/) as the signature mechanism. At this moment we cannot verify a Blockcerts V3 in vc.js for instance as MerkleProof2019 does not exist in the security vocab. For dev mode I edited my local npm package, but that will not be sustainable in the outer world.

I had had conversations with @msporny back in March on the subject, and while I imagine it's too late to bring that into the v2 definition, I think it could be brought in to the v3 one. But I wanted confirmation it was still ok to do so before opening a PR out of the blue.

cc @kimdhamilton and Dmitry Semenovskiy for visibility

**Comment by msporny** [comment]
Yes, still ok to do in v3. Please raise a PR as MerkleProof2019 is an interesting cryptosuite that demonstrates that not every proof needs to be a digital signature. :)

**Comment by lemoustachiste** [comment]
Great, 

Thanks for the answer, I'll work on that soon
