### ISSUE TITLE
Missing comma in example 31

### ISSUE THREAD

**Issue by bblfish** [w3c-ccg/security-vocab#92]
I am trying to understand the security vocabulary, and so am going through examples turning them into Turtle, 
Doing that, I found a missing comma in example 31.

```
{
  "@context": [
    "https://w3id.org/security/v1",
    { "ex": "http://example.org/vocab#" }
  ],
  "@graph": {
    "ex:request": "DELETE /private/2840-credit-card-log"
  }
  "signature": {
    "@type": "GraphSignature2012",
    "creator": "http://example.com/people/john-doe#key-5",
    "nonce": "8495723045.84957",
    "signatureValue": "Q3ODIyOGQzNGVkMzVm4NTIyZ43OWM32NjITkZDYMmMzQzNmExMgoYzI="
  }
}
```

It would be nice if each of the examples were placed in its own `curl`able file. Then you could run tests on each of the examples to make sure they correct. It would also make it easier to try these out from command line tools.

**Comment by TallTed** [comment]
Probably not as fast as your suggested command-line testing, but the [JSON-LD Playground](https://json-ld.org/playground/) provides a quick copy-and-paste test environment.
